// Code generated by "stringer -type TaskAction"; DO NOT EDIT.

package pkg

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Edit-0]
	_ = x[Commit-1]
	_ = x[Swap-2]
	_ = x[Score-3]
	_ = x[Delete-4]
	_ = x[Cancel-5]
}

const _TaskAction_name = "EditCommitSwapScoreDeleteCancel"

var _TaskAction_index = [...]uint8{0, 4, 10, 14, 19, 25, 31}

func (i TaskAction) String() string {
	if i < 0 || i >= TaskAction(len(_TaskAction_index)-1) {
		return "TaskAction(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TaskAction_name[_TaskAction_index[i]:_TaskAction_index[i+1]]
}
